stages:
  - compile
  - deploy

build:
  stage: compile
  image: node:14.15.5-buster
  allow_failure: false
  before_script:
    - echo $DEV > .env
    - apt-get update
    - apt-get install -y zip unzip curl
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install > /dev/null
    - chmod +x ./install.sh
  script:
    - ./install.sh
    - zip -q deployments-$CI_COMMIT_REF_SLUG.zip -r deployments
    - aws s3 sync deployments-$CI_COMMIT_REF_SLUG.zip s3://onchain-deployments
  after_script:
    - rm .env
  only:
    refs:
      - development

deploy:
  stage: deploy
  image: ubuntu
  allow_failure: false
  before_script:
    - apt-get update
    - apt-get install -y curl
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=$CI_COMMIT_REF_SLUG "https://gitlab.com/api/v4/projects/26457710/trigger/pipeline"
  only:
    refs:
      - development
  dependencies:
    - build
